"""Incremental Cash Flow method.

Values an intangible asset as the present value of the difference
between cash flows with and without the asset.

Implements the method from Chapter 4.
"""

from __future__ import annotations

from intangible_valuation.core.time_value import present_value_of_series


def incremental_cashflow(
    cash_flows_with: list[float],
    cash_flows_without: list[float],
    discount_rate: float,
) -> dict:
    """Calculate asset value using the Incremental Cash Flow method.

    The Incremental Cash Flow method values an intangible asset as the
    present value of the additional cash flows generated by having the
    asset versus not having it.

    Formula:
        For each period t:
            Incremental_CF_t = CashFlow_with_t - CashFlow_without_t
            PV_t = Incremental_CF_t / (1 + discount_rate)^t

        Value = sum(PV_t)

    Args:
        cash_flows_with: Projected cash flows with the asset.
        cash_flows_without: Projected cash flows without the asset.
            Must be the same length as cash_flows_with.
        discount_rate: Discount rate as decimal. Must be positive.

    Returns:
        Dict with:
            - value: Present value of incremental cash flows
            - method: 'Incremental Cash Flow'
            - formula_reference: 'Chapter 4: Income Methods - Incremental Cash Flow'
            - incremental_cash_flows: List of period-by-period differences
            - steps: List of calculation steps
            - assumptions: Key assumptions used

    Raises:
        ValueError: If inputs are invalid or inconsistent.

    Example:
        >>> result = incremental_cashflow(
        ...     cash_flows_with=[500000, 550000, 600000, 650000, 700000],
        ...     cash_flows_without=[400000, 420000, 440000, 460000, 480000],
        ...     discount_rate=0.10,
        ... )
        >>> result["value"] > 0
        True
    """
    if not cash_flows_with:
        raise ValueError("cash_flows_with cannot be empty")
    if len(cash_flows_with) != len(cash_flows_without):
        raise ValueError(
            f"cash_flows_with length ({len(cash_flows_with)}) must match "
            f"cash_flows_without length ({len(cash_flows_without)})"
        )
    if discount_rate <= 0:
        raise ValueError(f"discount_rate must be positive, got {discount_rate}")

    n = len(cash_flows_with)
    incremental = []
    steps = [
        f"Projection periods: {n}",
        f"Discount rate: {discount_rate:.2%}",
    ]
    steps.append("Period-by-period incremental cash flow calculation:")

    for i, (cf_with, cf_without) in enumerate(zip(cash_flows_with, cash_flows_without, strict=False), start=1):
        incr = cf_with - cf_without
        incremental.append(incr)
        steps.append(
            f"  Period {i}: with=${cf_with:,.2f}, without=${cf_without:,.2f}, "
            f"incremental=${incr:,.2f}"
        )

    pv_result = present_value_of_series(incremental, discount_rate)
    value = pv_result["present_value"]

    steps.append(f"PV of incremental cash flows: ${value:,.2f}")

    assumptions = [
        "Cash flows with the asset reflect the asset's contribution",
        "Cash flows without the asset represent the counterfactual scenario",
        "The difference is attributable solely to the subject asset",
        "Discount rate reflects the risk of the incremental cash flows",
        "Both scenarios use consistent assumptions and projections",
    ]

    return {
        "value": value,
        "method": "Incremental Cash Flow",
        "formula_reference": "Chapter 4: Income Methods - Incremental Cash Flow",
        "incremental_cash_flows": incremental,
        "steps": steps,
        "assumptions": assumptions,
    }
