import type { MethodDefinition, MethodParameter } from "./types";

const n = (name: string, description: string, opts?: Partial<MethodParameter>): MethodParameter => ({
  name,
  type: "number",
  required: true,
  description,
  ...opts,
});

const i = (name: string, description: string, opts?: Partial<MethodParameter>): MethodParameter => ({
  name,
  type: "integer",
  required: true,
  description,
  ...opts,
});

const rate = (name: string, description: string, opts?: Partial<MethodParameter>): MethodParameter => ({
  name,
  type: "number",
  required: true,
  description,
  minimum: 0,
  maximum: 1,
  ...opts,
});

const arr = (name: string, description: string, opts?: Partial<MethodParameter>): MethodParameter => ({
  name,
  type: "number[]",
  required: true,
  description,
  ...opts,
});

const json = (name: string, description: string, opts?: Partial<MethodParameter>): MethodParameter => ({
  name,
  type: "json",
  required: true,
  description,
  ...opts,
});

export const CATALOG: MethodDefinition[] = [
  // ---- Core — Time Value of Money ----------------------------------------
  {
    slug: "present-value",
    name: "Present Value",
    category: "core",
    description: "Present value of a future cash flow",
    formulaTex: "PV = FV / (1+r)^n",
    textbookReference: "Ch 2, Section 2.1",
    complexity: "basic",
    mcpTool: "present_value",
    pythonFunction: "intangible_valuation.core.time_value.present_value",
    parameters: [n("future_value", "Future value of the cash flow"), rate("discount_rate", "Annual discount rate"), i("periods", "Number of periods")],
  },
  {
    slug: "future-value",
    name: "Future Value",
    category: "core",
    description: "Future value of a present sum",
    formulaTex: "FV = PV * (1+r)^n",
    textbookReference: "Ch 2, Section 2.1",
    complexity: "basic",
    mcpTool: "future_value",
    pythonFunction: "intangible_valuation.core.time_value.future_value",
    parameters: [n("present_value", "Present value"), rate("discount_rate", "Annual rate"), i("periods", "Number of periods")],
  },
  {
    slug: "annuity-pv",
    name: "Annuity PV",
    category: "core",
    description: "Present value of an annuity",
    formulaTex: "PV = PMT * [1-(1+r)^(-n)] / r",
    textbookReference: "Ch 2, Section 2.2",
    complexity: "basic",
    mcpTool: "annuity_pv",
    pythonFunction: "intangible_valuation.core.time_value.annuity_pv",
    parameters: [n("payment", "Periodic payment"), rate("discount_rate", "Annual discount rate"), i("periods", "Number of periods")],
  },
  {
    slug: "perpetuity-pv",
    name: "Perpetuity PV",
    category: "core",
    description: "Present value of a perpetuity",
    formulaTex: "PV = PMT / r",
    textbookReference: "Ch 2, Section 2.2",
    complexity: "basic",
    mcpTool: "perpetuity_pv",
    pythonFunction: "intangible_valuation.core.time_value.perpetuity_pv",
    parameters: [n("payment", "Annual payment"), rate("discount_rate", "Annual discount rate")],
  },
  {
    slug: "growing-annuity-pv",
    name: "Growing Annuity PV",
    category: "core",
    description: "Present value of a growing annuity",
    formulaTex: "PV = PMT * [1-((1+g)/(1+r))^n]/(r-g)",
    textbookReference: "Ch 2, Section 2.2",
    complexity: "basic",
    mcpTool: "growing_annuity_pv",
    pythonFunction: "intangible_valuation.core.time_value.growing_annuity_pv",
    parameters: [n("payment", "First payment"), rate("discount_rate", "Annual discount rate"), rate("growth_rate", "Annual growth rate"), i("periods", "Number of periods")],
  },
  {
    slug: "terminal-value",
    name: "Terminal Value",
    category: "core",
    description: "Terminal value via Gordon Growth or Exit Multiple",
    formulaTex: "TV = FCF*(1+g)/(r-g)",
    textbookReference: "Ch 2, Section 2.4",
    complexity: "intermediate",
    mcpTool: "terminal_value",
    pythonFunction: "intangible_valuation.core.time_value.terminal_value",
    parameters: [
      n("final_year_cashflow", "Final-year free cash flow"),
      rate("perpetual_growth_rate", "Perpetual growth rate"),
      rate("discount_rate", "Discount rate"),
      n("exit_multiple", "Exit multiple (optional, overrides Gordon Growth)", { required: false }),
    ],
  },

  // ---- Core — Discount Rates ---------------------------------------------
  {
    slug: "build-up-discount-rate",
    name: "Build-Up Discount Rate",
    category: "core",
    description: "Build-up method: risk-free + premiums",
    formulaTex: "r = Rf + ERP + Size + Industry + Specific",
    textbookReference: "Ch 2, Section 2.3",
    complexity: "basic",
    mcpTool: "build_up_discount_rate",
    pythonFunction: "intangible_valuation.core.discount_rates.build_up_discount_rate",
    parameters: [
      rate("risk_free_rate", "Risk-free rate"),
      rate("equity_risk_premium", "Equity risk premium"),
      n("size_premium", "Size premium", { required: false, default: 0 }),
      n("industry_risk_premium", "Industry risk premium", { required: false, default: 0 }),
      n("specific_risk_premium", "Company-specific risk premium", { required: false, default: 0 }),
    ],
  },
  {
    slug: "capm",
    name: "CAPM",
    category: "core",
    description: "Capital Asset Pricing Model",
    formulaTex: "r = Rf + Beta*(Rm-Rf)",
    textbookReference: "Ch 2, Section 2.3",
    complexity: "basic",
    mcpTool: "capm",
    pythonFunction: "intangible_valuation.core.discount_rates.capm_discount_rate",
    parameters: [rate("risk_free_rate", "Risk-free rate"), n("beta", "Beta coefficient", { minimum: 0 }), rate("market_return", "Expected market return")],
  },
  {
    slug: "wacc",
    name: "WACC",
    category: "core",
    description: "Weighted Average Cost of Capital",
    formulaTex: "WACC = (E/V)*Re + (D/V)*Rd*(1-Tc)",
    textbookReference: "Ch 2, Section 2.3",
    complexity: "intermediate",
    mcpTool: "wacc",
    pythonFunction: "intangible_valuation.core.discount_rates.wacc",
    parameters: [
      n("equity_value", "Market value of equity"),
      n("debt_value", "Market value of debt"),
      rate("cost_of_equity", "Cost of equity"),
      rate("cost_of_debt", "Cost of debt"),
      rate("tax_rate", "Corporate tax rate"),
    ],
  },
  {
    slug: "tax-amortization-benefit",
    name: "Tax Amortization Benefit",
    category: "core",
    description: "TAB calculation for intangible assets",
    textbookReference: "Ch 3, Section 3.4",
    complexity: "intermediate",
    mcpTool: "tax_amortization_benefit",
    pythonFunction: "intangible_valuation.core.discount_rates.tax_amortization_benefit",
    parameters: [rate("discount_rate", "Discount rate"), i("useful_life", "Useful life in years"), rate("tax_rate", "Tax rate"), n("asset_value", "Asset value")],
  },
  {
    slug: "control-premium",
    name: "Control Premium",
    category: "core",
    description: "Premium for controlling interest",
    textbookReference: "Ch 3, Section 3.5",
    complexity: "basic",
    mcpTool: "control_premium",
    pythonFunction: "intangible_valuation.core.discount_rates.control_premium",
    parameters: [n("minority_price", "Minority interest price"), n("control_price", "Control interest price")],
  },
  {
    slug: "dlom-finnerty",
    name: "DLOM (Finnerty)",
    category: "core",
    description: "Discount for Lack of Marketability (Finnerty model)",
    textbookReference: "Ch 3, Section 3.5",
    complexity: "intermediate",
    mcpTool: "dlom_finnerty",
    pythonFunction: "intangible_valuation.core.discount_rates.dlom_finnerty",
    parameters: [n("restricted_period", "Restricted period (years)"), rate("volatility", "Volatility"), rate("risk_free_rate", "Risk-free rate")],
  },
  {
    slug: "currency-adjusted-discount-rate",
    name: "Currency-Adjusted Discount Rate",
    category: "core",
    description: "Adjust discount rates for currency risk",
    textbookReference: "Ch 16",
    complexity: "intermediate",
    mcpTool: "currency_adjusted_discount_rate",
    pythonFunction: "intangible_valuation.core.discount_rates.currency_adjusted_discount_rate",
    parameters: [
      rate("base_rate", "Base discount rate"),
      n("currency_risk_premium", "Currency risk premium", { required: false, default: 0 }),
      n("country_risk_premium", "Country risk premium", { required: false, default: 0 }),
    ],
  },

  // ---- Approaches — Cost --------------------------------------------------
  {
    slug: "reproduction-cost",
    name: "Reproduction Cost",
    category: "approaches",
    description: "Cost to reproduce an exact replica",
    textbookReference: "Ch 3, Section 3.1",
    complexity: "intermediate",
    mcpTool: "reproduction_cost",
    pythonFunction: "intangible_valuation.approaches.cost_approach.reproduction_cost",
    parameters: [
      json("development_costs", "JSON object of development costs (e.g. {\"labor\": 100000, \"materials\": 50000})"),
      json("obsolescence_factors", "JSON object of obsolescence factors {\"functional\":0.1,\"technological\":0.2,\"economic\":0.1}", { required: false }),
    ],
  },
  {
    slug: "replacement-cost",
    name: "Replacement Cost",
    category: "approaches",
    description: "Cost to replace with equivalent utility",
    textbookReference: "Ch 3, Section 3.1",
    complexity: "intermediate",
    mcpTool: "replacement_cost",
    pythonFunction: "intangible_valuation.approaches.cost_approach.replacement_cost",
    parameters: [
      n("current_cost", "Current replacement cost"),
      json("obsolescence_factors", "JSON object of obsolescence factors", { required: false }),
    ],
  },
  {
    slug: "market-approach-comparables",
    name: "Market Approach Comparables",
    category: "approaches",
    description: "Valuation based on comparable transactions",
    textbookReference: "Ch 3, Section 3.2",
    complexity: "intermediate",
    mcpTool: "market_approach_comparables",
    pythonFunction: "intangible_valuation.approaches.market_approach.market_approach_comparables",
    parameters: [
      json("comparables", "JSON array of {sale_price, revenue, asset_type}"),
      n("subject_revenue", "Subject asset revenue"),
      json("adjustments", "JSON object mapping comparable index to adjustment factor", { required: false }),
    ],
  },
  {
    slug: "royalty-capitalization",
    name: "Royalty Capitalization",
    category: "approaches",
    description: "Capitalized royalty-based valuation",
    textbookReference: "Ch 4, Section 4.3",
    complexity: "intermediate",
    mcpTool: "royalty_capitalization",
    pythonFunction: "intangible_valuation.approaches.market_approach.royalty_capitalization",
    parameters: [n("revenue", "Annual revenue"), rate("royalty_rate", "Royalty rate"), rate("discount_rate", "Discount rate")],
  },

  // ---- Income Methods -----------------------------------------------------
  {
    slug: "relief-from-royalty",
    name: "Relief from Royalty",
    category: "income_methods",
    description: "Value based on hypothetical royalty savings",
    formulaTex: "PV = SUM(R_t * r * (1-T) / (1+d)^t) * TAB",
    textbookReference: "Ch 4, Section 4.2",
    complexity: "intermediate",
    mcpTool: "relief_from_royalty",
    pythonFunction: "intangible_valuation.income_methods.relief_from_royalty.relief_from_royalty",
    parameters: [
      arr("revenue_projections", "Projected revenues per period (comma-separated)"),
      rate("royalty_rate", "Arm's length royalty rate"),
      rate("discount_rate", "Annual discount rate"),
      rate("tax_rate", "Effective tax rate"),
      i("useful_life", "Useful life in years"),
      { name: "tab_enabled", type: "boolean", required: false, default: true, description: "Apply Tax Amortization Benefit" },
    ],
  },
  {
    slug: "mpeem",
    name: "MPEEM",
    category: "income_methods",
    description: "Multi-Period Excess Earnings Method",
    textbookReference: "Ch 4, Section 4.1",
    complexity: "advanced",
    mcpTool: "mpeem",
    pythonFunction: "intangible_valuation.income_methods.excess_earnings.mpeem",
    parameters: [
      arr("cash_flow_projections", "Projected cash flows per period (comma-separated)"),
      json("contributory_asset_charges", "JSON array of contributory asset charge objects"),
      rate("discount_rate", "Discount rate"),
      rate("tax_rate", "Tax rate"),
    ],
  },
  {
    slug: "single-period-excess-earnings",
    name: "Single-Period Excess Earnings",
    category: "income_methods",
    description: "Single-period variant of excess earnings",
    textbookReference: "Ch 4, Section 4.1",
    complexity: "intermediate",
    mcpTool: "single_period_excess_earnings",
    pythonFunction: "intangible_valuation.income_methods.excess_earnings.single_period_excess_earnings",
    parameters: [
      n("normalized_earnings", "Normalized earnings"),
      json("contributory_asset_charges", "JSON array of contributory asset charge objects"),
      rate("capitalization_rate", "Capitalization rate"),
    ],
  },
  {
    slug: "contributory-asset-charges",
    name: "Contributory Asset Charges",
    category: "income_methods",
    description: "Calculate charges for contributory assets",
    textbookReference: "Ch 4, Section 4.1",
    complexity: "intermediate",
    mcpTool: "contributory_asset_charges",
    pythonFunction: "intangible_valuation.income_methods.excess_earnings.contributory_asset_charges",
    parameters: [json("assets", "JSON array of {name, value, rate} asset objects")],
  },
  {
    slug: "incremental-cashflow",
    name: "Incremental Cash Flow",
    category: "income_methods",
    description: "Value based on incremental cash flows",
    textbookReference: "Ch 4, Section 4.4",
    complexity: "intermediate",
    mcpTool: "incremental_cashflow",
    pythonFunction: "intangible_valuation.income_methods.incremental_cashflow.incremental_cashflow",
    parameters: [
      arr("cash_flows_with", "Cash flows with the asset (comma-separated)"),
      arr("cash_flows_without", "Cash flows without the asset (comma-separated)"),
      rate("discount_rate", "Discount rate"),
    ],
  },

  // ---- Asset Types — IP ---------------------------------------------------
  {
    slug: "patent-valuation",
    name: "Patent Valuation",
    category: "asset_types",
    description: "Value patents using multiple methods",
    textbookReference: "Ch 5",
    complexity: "advanced",
    mcpTool: "patent_valuation",
    pythonFunction: "intangible_valuation.asset_types.ip_valuation.patent_valuation",
    parameters: [
      i("remaining_life", "Remaining patent life in years"),
      arr("cash_flow_projections", "Projected annual cash flows (comma-separated)"),
      rate("probability_of_success", "Probability of commercial success"),
      rate("discount_rate", "Discount rate"),
      arr("comparable_license_rates", "Comparable license royalty rates (comma-separated)", { required: false }),
    ],
  },
  {
    slug: "copyright-valuation",
    name: "Copyright Valuation",
    category: "asset_types",
    description: "Value copyrights",
    textbookReference: "Ch 5",
    complexity: "intermediate",
    mcpTool: "copyright_valuation",
    pythonFunction: "intangible_valuation.asset_types.ip_valuation.copyright_valuation",
    parameters: [
      n("projected_revenue", "Projected annual revenue"),
      i("useful_life", "Useful life in years"),
      rate("discount_rate", "Discount rate"),
      rate("royalty_rate", "Royalty rate"),
    ],
  },
  {
    slug: "trade-secret-valuation",
    name: "Trade Secret Valuation",
    category: "asset_types",
    description: "Value trade secrets",
    textbookReference: "Ch 5",
    complexity: "intermediate",
    mcpTool: "trade_secret_valuation",
    pythonFunction: "intangible_valuation.asset_types.ip_valuation.trade_secret_valuation",
    parameters: [
      n("development_cost", "Development cost"),
      i("economic_life", "Economic life in years"),
      i("competitive_advantage_period", "Competitive advantage period in years"),
      rate("discount_rate", "Discount rate"),
      rate("secrecy_probability", "Probability the secret remains undisclosed"),
    ],
  },
  {
    slug: "patent-portfolio-valuation",
    name: "Patent Portfolio Valuation",
    category: "asset_types",
    description: "Value an entire patent portfolio",
    textbookReference: "Ch 5",
    complexity: "advanced",
    mcpTool: "patent_portfolio_valuation",
    pythonFunction: "intangible_valuation.asset_types.ip_valuation.patent_portfolio_valuation",
    parameters: [
      json("patents", "JSON array of {value, category?, remaining_life?}"),
      n("diversification_factor", "Diversification adjustment factor", { required: false, default: 0.1 }),
    ],
  },
  {
    slug: "option-pricing-patent",
    name: "Option Pricing for Patents",
    category: "asset_types",
    description: "Patent valuation using option pricing",
    textbookReference: "Ch 5",
    complexity: "advanced",
    mcpTool: "option_pricing_patent",
    pythonFunction: "intangible_valuation.asset_types.ip_valuation.option_pricing_patent",
    parameters: [
      n("exercise_cost", "Exercise cost"),
      n("expected_value", "Expected value"),
      rate("volatility", "Volatility"),
      n("time_to_expiry", "Time to expiry (years)"),
      rate("risk_free_rate", "Risk-free rate"),
    ],
  },

  // ---- Asset Types — Brand ------------------------------------------------
  {
    slug: "trademark-valuation",
    name: "Trademark Valuation",
    category: "asset_types",
    description: "Value trademarks",
    textbookReference: "Ch 6",
    complexity: "intermediate",
    mcpTool: "trademark_valuation",
    pythonFunction: "intangible_valuation.asset_types.brand_valuation.trademark_valuation",
    parameters: [
      n("revenue", "Annual revenue"),
      rate("profit_margin", "Profit margin"),
      rate("brand_strength_index", "Brand strength index (0-1)"),
      rate("discount_rate", "Discount rate"),
      i("useful_life", "Useful life in years"),
    ],
  },
  {
    slug: "brand-strength-index",
    name: "Brand Strength Index",
    category: "asset_types",
    description: "Interbrand-style brand strength assessment",
    textbookReference: "Ch 6",
    complexity: "intermediate",
    mcpTool: "brand_strength_index",
    pythonFunction: "intangible_valuation.asset_types.brand_valuation.brand_strength_index",
    parameters: [
      rate("revenue_stability", "Revenue stability score"),
      rate("market_share", "Market share score"),
      rate("geographic_reach", "Geographic reach score"),
      rate("customer_loyalty", "Customer loyalty score"),
      rate("investment_level", "Investment level score"),
    ],
  },
  {
    slug: "interbrand-brand-valuation",
    name: "Interbrand Brand Valuation",
    category: "asset_types",
    description: "Full Interbrand brand valuation methodology",
    textbookReference: "Ch 6",
    complexity: "advanced",
    mcpTool: "interbrand_brand_valuation",
    pythonFunction: "intangible_valuation.asset_types.brand_valuation.interbrand_brand_valuation",
    parameters: [
      n("brand_earnings", "Brand earnings"),
      rate("role_of_brand_index", "Role of brand index"),
      n("brand_strength_score", "Brand strength score (0-100)"),
      rate("discount_rate", "Discount rate"),
    ],
  },
  {
    slug: "brand-royalty-rate-from-comparables",
    name: "Brand Royalty Rate from Comparables",
    category: "asset_types",
    description: "Derive brand royalty rate from market data",
    textbookReference: "Ch 6",
    complexity: "intermediate",
    mcpTool: "brand_royalty_rate_from_comparables",
    pythonFunction: "intangible_valuation.asset_types.brand_valuation.brand_royalty_rate_from_comparables",
    parameters: [
      arr("comparable_rates", "Comparable brand royalty rates (comma-separated)"),
      n("brand_strength_adjustment", "Brand strength adjustment (-0.5 to +0.5)", { required: false, default: 0, minimum: -0.5, maximum: 0.5 }),
    ],
  },

  // ---- Asset Types — Technology -------------------------------------------
  {
    slug: "developed-technology-valuation",
    name: "Developed Technology Valuation",
    category: "asset_types",
    description: "Value developed/proprietary technology",
    textbookReference: "Ch 7",
    complexity: "advanced",
    mcpTool: "developed_technology_valuation",
    pythonFunction: "intangible_valuation.asset_types.technology_valuation.developed_technology_valuation",
    parameters: [
      n("rd_costs", "R&D costs"),
      { name: "life_cycle_stage", type: "string", required: true, description: "Life-cycle stage (e.g. development, growth, mature)" },
      i("competitive_advantage", "Competitive advantage (years)"),
      rate("discount_rate", "Discount rate"),
      arr("cash_flow_projections", "Projected cash flows (comma-separated)"),
    ],
  },
  {
    slug: "software-valuation",
    name: "Software Valuation",
    category: "asset_types",
    description: "Value software assets",
    textbookReference: "Ch 7",
    complexity: "intermediate",
    mcpTool: "software_valuation",
    pythonFunction: "intangible_valuation.asset_types.technology_valuation.software_valuation",
    parameters: [
      n("development_cost", "Development cost"),
      n("maintenance_cost", "Maintenance cost"),
      i("user_base", "User base"),
      json("revenue_model", "JSON object describing the revenue model"),
      i("useful_life", "Useful life in years"),
      rate("discount_rate", "Discount rate"),
    ],
  },
  {
    slug: "data-asset-valuation",
    name: "Data Asset Valuation",
    category: "asset_types",
    description: "Value data sets and databases",
    textbookReference: "Ch 7",
    complexity: "advanced",
    mcpTool: "data_asset_valuation",
    pythonFunction: "intangible_valuation.asset_types.technology_valuation.data_asset_valuation",
    parameters: [
      n("acquisition_cost", "Acquisition cost"),
      rate("quality_score", "Data quality score"),
      n("revenue_contribution", "Revenue contribution"),
      i("useful_life", "Useful life in years"),
      rate("discount_rate", "Discount rate"),
    ],
  },
  {
    slug: "platform-valuation",
    name: "Platform Valuation",
    category: "asset_types",
    description: "Value platform/network effect assets",
    textbookReference: "Ch 7",
    complexity: "advanced",
    mcpTool: "platform_valuation",
    pythonFunction: "intangible_valuation.asset_types.technology_valuation.platform_valuation",
    parameters: [
      i("network_size", "Network size"),
      n("network_effects_coefficient", "Network effects coefficient"),
      n("revenue_per_user", "Revenue per user"),
      rate("growth_rate", "Growth rate"),
      rate("discount_rate", "Discount rate"),
    ],
  },
  {
    slug: "technology-obsolescence-curve",
    name: "Technology Obsolescence Curve",
    category: "asset_types",
    description: "Model technology obsolescence",
    textbookReference: "Ch 7",
    complexity: "intermediate",
    mcpTool: "technology_obsolescence_curve",
    pythonFunction: "intangible_valuation.asset_types.technology_valuation.technology_obsolescence_curve",
    parameters: [n("initial_value", "Initial value"), rate("obsolescence_rate", "Obsolescence rate"), i("periods", "Number of periods")],
  },
  {
    slug: "algorithm-valuation",
    name: "Algorithm Valuation",
    category: "asset_types",
    description: "Value proprietary algorithms",
    textbookReference: "Ch 7",
    complexity: "intermediate",
    mcpTool: "algorithm_valuation",
    pythonFunction: "intangible_valuation.asset_types.technology_valuation.algorithm_valuation",
    parameters: [
      n("computational_savings", "Computational savings"),
      n("deployment_scale", "Deployment scale"),
      i("competitive_advantage_years", "Competitive advantage in years"),
      rate("discount_rate", "Discount rate"),
    ],
  },

  // ---- Asset Types — Customer ---------------------------------------------
  {
    slug: "customer-relationship-valuation",
    name: "Customer Relationship Valuation",
    category: "asset_types",
    description: "Value customer relationships",
    textbookReference: "Ch 8",
    complexity: "intermediate",
    mcpTool: "customer_relationship_valuation",
    pythonFunction: "intangible_valuation.asset_types.customer_valuation.customer_relationship_valuation",
    parameters: [
      i("customer_count", "Number of customers"),
      n("avg_revenue_per_customer", "Average revenue per customer"),
      rate("retention_rate", "Retention rate"),
      rate("profit_margin", "Profit margin"),
      rate("discount_rate", "Discount rate"),
      i("projection_period", "Projection period in years"),
    ],
  },
  {
    slug: "distribution-network-valuation",
    name: "Distribution Network Valuation",
    category: "asset_types",
    description: "Value distribution networks",
    textbookReference: "Ch 8",
    complexity: "intermediate",
    mcpTool: "distribution_network_valuation",
    pythonFunction: "intangible_valuation.asset_types.customer_valuation.distribution_network_valuation",
    parameters: [
      i("channel_count", "Number of channels"),
      n("revenue_per_channel", "Revenue per channel"),
      rate("channel_margin", "Channel margin"),
      i("useful_life", "Useful life in years"),
      rate("discount_rate", "Discount rate"),
    ],
  },
  {
    slug: "non-compete-valuation",
    name: "Non-Compete Valuation",
    category: "asset_types",
    description: "Value non-compete agreements",
    textbookReference: "Ch 8",
    complexity: "intermediate",
    mcpTool: "non_compete_valuation",
    pythonFunction: "intangible_valuation.asset_types.customer_valuation.non_compete_valuation",
    parameters: [
      n("protected_revenue", "Protected revenue"),
      rate("profit_margin", "Profit margin"),
      i("term", "Non-compete term in years"),
      rate("enforcement_probability", "Enforcement probability"),
      rate("discount_rate", "Discount rate"),
    ],
  },
  {
    slug: "customer-lifetime-value",
    name: "Customer Lifetime Value (CLV)",
    category: "asset_types",
    description: "Calculate customer lifetime value",
    textbookReference: "Ch 8",
    complexity: "intermediate",
    mcpTool: "customer_lifetime_value",
    pythonFunction: "intangible_valuation.asset_types.customer_valuation.customer_lifetime_value",
    parameters: [
      n("revenue_per_period", "Revenue per period"),
      rate("retention_rate", "Retention rate"),
      rate("discount_rate", "Discount rate"),
      rate("margin", "Margin"),
    ],
  },
  {
    slug: "backlog-valuation",
    name: "Backlog Valuation",
    category: "asset_types",
    description: "Value order backlogs",
    textbookReference: "Ch 8",
    complexity: "basic",
    mcpTool: "backlog_valuation",
    pythonFunction: "intangible_valuation.asset_types.customer_valuation.backlog_valuation",
    parameters: [
      json("contract_backlog", "JSON array of backlog contract objects"),
      rate("probability_of_completion", "Probability of completion"),
      rate("discount_rate", "Discount rate"),
    ],
  },
  {
    slug: "churn-impact-analysis",
    name: "Churn Impact Analysis",
    category: "asset_types",
    description: "Analyze impact of customer churn on value",
    textbookReference: "Ch 8",
    complexity: "intermediate",
    mcpTool: "churn_impact_analysis",
    pythonFunction: "intangible_valuation.asset_types.customer_valuation.churn_impact_analysis",
    parameters: [
      i("current_customers", "Current customers"),
      rate("churn_rate_before", "Churn rate before"),
      rate("churn_rate_after", "Churn rate after"),
      n("revenue_per_customer", "Revenue per customer"),
      rate("discount_rate", "Discount rate"),
    ],
  },

  // ---- Asset Types — Human Capital ----------------------------------------
  {
    slug: "assembled-workforce-valuation",
    name: "Assembled Workforce Valuation",
    category: "asset_types",
    description: "Value assembled workforce",
    textbookReference: "Ch 9",
    complexity: "intermediate",
    mcpTool: "assembled_workforce_valuation",
    pythonFunction: "intangible_valuation.asset_types.human_capital.assembled_workforce_valuation",
    parameters: [
      i("employee_count", "Employee count"),
      n("avg_replacement_cost", "Average replacement cost"),
      n("training_cost", "Training cost"),
      rate("productivity_factor", "Productivity factor"),
      rate("attrition_rate", "Attrition rate"),
    ],
  },
  {
    slug: "key-person-value",
    name: "Key Person Value",
    category: "asset_types",
    description: "Value of a key individual",
    textbookReference: "Ch 9",
    complexity: "intermediate",
    mcpTool: "key_person_value",
    pythonFunction: "intangible_valuation.asset_types.human_capital.key_person_value",
    parameters: [
      n("revenue_contribution", "Revenue contribution"),
      n("replacement_cost", "Replacement cost"),
      rate("departure_probability", "Departure probability"),
      rate("discount_rate", "Discount rate"),
    ],
  },

  // ---- Advanced — Goodwill & PPA ------------------------------------------
  {
    slug: "goodwill",
    name: "Goodwill Calculation",
    category: "advanced",
    description: "Calculate goodwill = purchase price - FV of net assets",
    textbookReference: "Ch 10, ASC 805",
    complexity: "intermediate",
    mcpTool: "goodwill",
    pythonFunction: "intangible_valuation.advanced.goodwill.goodwill",
    parameters: [n("purchase_price", "Purchase price"), n("fair_value_net_identifiable_assets", "Fair value of net identifiable assets")],
  },
  {
    slug: "purchase-price-allocation",
    name: "Purchase Price Allocation",
    category: "advanced",
    description: "PPA waterfall per ASC 805 / IFRS 3",
    textbookReference: "Ch 10, ASC 805",
    complexity: "advanced",
    mcpTool: "purchase_price_allocation",
    pythonFunction: "intangible_valuation.advanced.purchase_price_alloc.purchase_price_allocation",
    parameters: [
      n("purchase_price", "Purchase price"),
      n("tangible_assets_fv", "Fair value of tangible assets"),
      json("identified_intangibles", "JSON array of identified intangible {name, value}"),
    ],
  },
  {
    slug: "bargain-purchase-analysis",
    name: "Bargain Purchase Analysis",
    category: "advanced",
    description: "Analysis of bargain purchase (negative goodwill)",
    textbookReference: "Ch 10, ASC 805",
    complexity: "advanced",
    mcpTool: "bargain_purchase_analysis",
    pythonFunction: "intangible_valuation.advanced.purchase_price_alloc.bargain_purchase_analysis",
    parameters: [n("purchase_price", "Purchase price"), n("fair_value_net_assets", "Fair value of net assets")],
  },
  {
    slug: "contingent-consideration-valuation",
    name: "Contingent Consideration Valuation",
    category: "advanced",
    description: "Value earn-outs and contingent payments",
    textbookReference: "Ch 10, ASC 805",
    complexity: "advanced",
    mcpTool: "contingent_consideration_valuation",
    pythonFunction: "intangible_valuation.advanced.purchase_price_alloc.contingent_consideration_valuation",
    parameters: [json("scenarios", "JSON array of scenario {name, probability, payout}"), rate("discount_rate", "Discount rate")],
  },
  {
    slug: "deferred-tax-liability-ppa",
    name: "Deferred Tax Liability in PPA",
    category: "advanced",
    description: "DTL calculation for PPA",
    textbookReference: "Ch 10, ASC 805",
    complexity: "advanced",
    mcpTool: "deferred_tax_liability_ppa",
    pythonFunction: "intangible_valuation.advanced.purchase_price_alloc.deferred_tax_liability_ppa",
    parameters: [json("identified_intangibles", "JSON array of identified intangible {name, value}"), n("tax_basis", "Tax basis"), rate("statutory_rate", "Statutory tax rate")],
  },

  // ---- Advanced — Impairment ----------------------------------------------
  {
    slug: "goodwill-impairment-test",
    name: "Goodwill Impairment Test",
    category: "advanced",
    description: "ASC 350 / IAS 36 goodwill impairment testing",
    textbookReference: "Ch 11, ASC 350 / IAS 36",
    complexity: "advanced",
    mcpTool: "goodwill_impairment_test",
    pythonFunction: "intangible_valuation.advanced.impairment_testing.goodwill_impairment_test",
    parameters: [n("carrying_value", "Carrying value"), n("fair_value", "Fair value")],
  },
  {
    slug: "intangible-impairment-test",
    name: "Intangible Asset Impairment Test",
    category: "advanced",
    description: "Impairment testing for finite/indefinite-life intangibles",
    textbookReference: "Ch 11, ASC 350 / IAS 36",
    complexity: "advanced",
    mcpTool: "intangible_impairment_test",
    pythonFunction: "intangible_valuation.advanced.impairment_testing.intangible_impairment_test",
    parameters: [
      n("carrying_value", "Carrying value"),
      n("fair_value", "Fair value (ASC 350)", { required: false }),
      n("recoverable_amount", "Recoverable amount (IAS 36)", { required: false }),
      { name: "standard", type: "string", required: false, default: "ASC350", description: "Standard: ASC350 or IAS36" },
    ],
  },
  {
    slug: "value-in-use",
    name: "Value in Use",
    category: "advanced",
    description: "Calculate value in use for impairment",
    textbookReference: "Ch 11, IAS 36",
    complexity: "intermediate",
    mcpTool: "value_in_use",
    pythonFunction: "intangible_valuation.advanced.impairment_testing.value_in_use",
    parameters: [
      arr("cash_flow_projections", "Projected cash flows (comma-separated)"),
      rate("terminal_growth_rate", "Terminal growth rate"),
      rate("discount_rate", "Discount rate"),
    ],
  },
  {
    slug: "fair-value-less-costs-to-sell",
    name: "Fair Value Less Costs to Sell",
    category: "advanced",
    description: "Calculate FVLCS for impairment",
    textbookReference: "Ch 11, IAS 36",
    complexity: "intermediate",
    mcpTool: "fair_value_less_costs_to_sell",
    pythonFunction: "intangible_valuation.advanced.impairment_testing.fair_value_less_costs_to_sell",
    parameters: [n("fair_value", "Fair value"), n("disposal_costs", "Disposal costs")],
  },
  {
    slug: "cash-generating-unit-impairment",
    name: "CGU Impairment",
    category: "advanced",
    description: "Cash Generating Unit impairment test",
    textbookReference: "Ch 11, IAS 36",
    complexity: "advanced",
    mcpTool: "cash_generating_unit_impairment",
    pythonFunction: "intangible_valuation.advanced.impairment_testing.cash_generating_unit_impairment",
    parameters: [
      n("cgu_carrying_value", "CGU carrying value"),
      n("cgu_recoverable_amount", "CGU recoverable amount"),
      n("goodwill_allocated", "Goodwill allocated to CGU"),
      json("other_assets", "JSON array of other asset {name, value}"),
    ],
  },

  // ---- Advanced — Litigation ----------------------------------------------
  {
    slug: "patent-infringement-damages",
    name: "Patent Infringement Damages",
    category: "advanced",
    description: "Calculate damages for patent infringement",
    textbookReference: "Ch 15",
    complexity: "advanced",
    mcpTool: "patent_infringement_damages",
    pythonFunction: "intangible_valuation.advanced.litigation.patent_infringement_damages",
    parameters: [
      n("lost_profits_or_royalty", "Lost profits or royalty amount"),
      i("infringement_period", "Infringement period in years"),
      rate("discount_rate", "Discount rate"),
      rate("prejudgment_interest_rate", "Prejudgment interest rate"),
    ],
  },

  // ---- Advanced — Monte Carlo & Statistics ---------------------------------
  {
    slug: "monte-carlo-sensitivity",
    name: "Monte Carlo Sensitivity",
    category: "advanced",
    description: "Sensitivity analysis using Monte Carlo",
    textbookReference: "Ch 17",
    complexity: "advanced",
    mcpTool: "monte_carlo_sensitivity",
    pythonFunction: "intangible_valuation.advanced.monte_carlo.monte_carlo_sensitivity",
    parameters: [
      { name: "valuation_fn", type: "string", required: true, description: "Valuation function name (e.g. present_value, wacc, capm_discount_rate)" },
      json("base_params", "JSON object of base parameter values"),
      json("distributions", "JSON object mapping parameter to {distribution, params}"),
      i("iterations", "Number of iterations", { required: false, default: 10000 }),
      i("seed", "Random seed", { required: false }),
    ],
  },
  {
    slug: "monte-carlo-valuation",
    name: "Monte Carlo Valuation",
    category: "advanced",
    description: "Full Monte Carlo valuation simulation",
    textbookReference: "Ch 17",
    complexity: "advanced",
    mcpTool: "monte_carlo_valuation",
    pythonFunction: "intangible_valuation.core.statistics.monte_carlo_valuation",
    parameters: [
      { name: "valuation_fn", type: "string", required: true, description: "Valuation function name (e.g. present_value, wacc, capm_discount_rate)" },
      json("input_distributions", "JSON array of {name, distribution, params}"),
      i("iterations", "Number of iterations", { required: false, default: 10000 }),
      i("seed", "Random seed", { required: false }),
    ],
  },
  {
    slug: "decision-tree-valuation",
    name: "Decision Tree Valuation",
    category: "advanced",
    description: "Decision tree analysis for valuations",
    textbookReference: "Ch 17",
    complexity: "advanced",
    mcpTool: "decision_tree_valuation",
    pythonFunction: "intangible_valuation.core.statistics.decision_tree_valuation",
    parameters: [json("tree", "JSON object with nodes and edges arrays")],
  },
  {
    slug: "monte-carlo-with-correlation",
    name: "Monte Carlo with Correlation",
    category: "advanced",
    description: "Correlated variable Monte Carlo simulation",
    textbookReference: "Ch 17",
    complexity: "advanced",
    mcpTool: "monte_carlo_with_correlation",
    pythonFunction: "intangible_valuation.core.statistics.monte_carlo_with_correlation",
    parameters: [
      { name: "valuation_fn", type: "string", required: true, description: "Valuation function name (e.g. present_value, wacc, capm_discount_rate)" },
      json("distributions", "JSON array of {name, distribution, params}"),
      json("correlation_matrix", "JSON 2D array correlation matrix"),
      i("iterations", "Number of iterations", { required: false, default: 10000 }),
      i("seed", "Random seed", { required: false }),
    ],
  },
  {
    slug: "sensitivity-tornado",
    name: "Sensitivity Tornado Chart",
    category: "advanced",
    description: "Generate tornado chart for sensitivity analysis",
    textbookReference: "Ch 17",
    complexity: "intermediate",
    mcpTool: "sensitivity_tornado",
    pythonFunction: "intangible_valuation.core.statistics.sensitivity_tornado",
    parameters: [
      { name: "function_name", type: "string", required: true, description: "Name of the function to analyze" },
      json("base_params", "JSON object of base case parameters"),
      json("parameter_ranges", "JSON object mapping parameter to array of test values"),
    ],
  },
  {
    slug: "scenario-analysis",
    name: "Scenario Analysis",
    category: "advanced",
    description: "Multi-scenario valuation analysis",
    textbookReference: "Ch 17",
    complexity: "intermediate",
    mcpTool: "scenario_analysis",
    pythonFunction: "intangible_valuation.core.statistics.scenario_analysis",
    parameters: [json("scenarios", "JSON array of {name, probability, params, function_name}")],
  },

  // ---- Advanced — Transfer Pricing & Royalty --------------------------------
  {
    slug: "cup-transfer-price",
    name: "CUP Transfer Price",
    category: "advanced",
    description: "Comparable Uncontrolled Price for transfer pricing",
    textbookReference: "Ch 16, OECD TP",
    complexity: "advanced",
    mcpTool: "cup_transfer_price",
    pythonFunction: "intangible_valuation.advanced.transfer_pricing.cup_transfer_price",
    parameters: [n("controlled_price", "Controlled transaction price"), arr("uncontrolled_prices", "Uncontrolled comparable prices (comma-separated)")],
  },
  {
    slug: "royalty-rate-benchmark",
    name: "Royalty Rate Benchmark",
    category: "advanced",
    description: "Benchmark royalty rates from market data",
    textbookReference: "Ch 6, Section 6.3",
    complexity: "intermediate",
    mcpTool: "royalty_rate_benchmark",
    pythonFunction: "intangible_valuation.advanced.royalty_benchmark.royalty_rate_benchmark",
    parameters: [
      { name: "ip_type", type: "string", required: true, description: "IP type (e.g. patent, trademark, technology)" },
      { name: "industry", type: "string", required: true, description: "Industry (e.g. technology, pharma, saas)" },
    ],
  },
  {
    slug: "adjust-royalty-rate",
    name: "Adjust Royalty Rate",
    category: "advanced",
    description: "Adjust royalty rate for comparability",
    textbookReference: "Ch 6, Section 6.3",
    complexity: "intermediate",
    mcpTool: "adjust_royalty_rate",
    pythonFunction: "intangible_valuation.advanced.royalty_benchmark.adjust_royalty_rate",
    parameters: [
      rate("base_rate", "Base royalty rate"),
      json("adjustment_factors", "JSON object of factor name to multiplier (e.g. {\"profit_margin\": 1.2})"),
    ],
  },
  {
    slug: "twenty-five-percent-rule",
    name: "25% Rule",
    category: "advanced",
    description: "Traditional 25% rule for profit allocation",
    textbookReference: "Ch 6, Section 6.2",
    complexity: "basic",
    mcpTool: "twenty_five_percent_rule",
    pythonFunction: "intangible_valuation.advanced.royalty_benchmark.twenty_five_percent_rule",
    parameters: [n("licensee_expected_profit", "Licensee expected profit")],
  },
  {
    slug: "profit-split-method",
    name: "Profit Split Method",
    category: "advanced",
    description: "Transfer pricing profit split",
    textbookReference: "Ch 16, OECD TP",
    complexity: "advanced",
    mcpTool: "profit_split_method",
    pythonFunction: "intangible_valuation.advanced.royalty_benchmark.profit_split_method",
    parameters: [
      rate("licensor_contribution_pct", "Licensor contribution percentage"),
      rate("licensee_contribution_pct", "Licensee contribution percentage"),
      n("total_profit", "Total profit"),
    ],
  },
  {
    slug: "analytical-method-valuation",
    name: "Analytical Method Valuation",
    category: "advanced",
    description: "Analytical approach to valuation",
    textbookReference: "Appendix A",
    complexity: "advanced",
    mcpTool: "analytical_method_valuation",
    pythonFunction: "intangible_valuation.advanced.royalty_benchmark.analytical_method_valuation",
    parameters: [
      n("advantage_margin", "Advantage margin"),
      n("volume", "Volume"),
      rate("discount_rate", "Discount rate"),
      i("economic_life", "Economic life in years"),
    ],
  },
];

export const CATALOG_SLUGS: string[] = CATALOG.map((m) => m.slug);

export function getCatalogMethod(slug: string): MethodDefinition | undefined {
  return CATALOG.find((m) => m.slug === slug);
}
