"use client";

import { useState } from "react";
import { Download, Clipboard } from "lucide-react";
import type { ValuationResult } from "@/lib/valuation/types";

interface ExportButtonProps {
  result: ValuationResult;
}

export function ExportButton({ result }: ExportButtonProps) {
  const [showMenu, setShowMenu] = useState(false);

  const buildReportText = () => {
    return `Intangible Asset Valuation Report
=====================================
Method: ${result.method}
Value: $${result.value.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}

Formula: ${result.formula_reference}

Inputs:
${Object.entries(result.inputs)
  .map(([k, v]) => `  ${k}: ${JSON.stringify(v)}`)
  .join("\n")}

Steps:
${result.steps.map((s, i) => `  ${i + 1}. ${s}`).join("\n")}

Assumptions:
${result.assumptions.map((a) => `  - ${a}`).join("\n")}

Generated by Intangible Valuation Platform
https://intangible-valuation.simonmak.com`;
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildReportText());
    setShowMenu(false);
  };

  const handleDownloadPDF = () => {
    const report = buildReportText();
    const printWindow = window.open("", "_blank", "width=720,height=900");
    if (!printWindow) {
      window.print();
      setShowMenu(false);
      return;
    }
    printWindow.document.write(`<!doctype html>
<html><head><title>Valuation Report — ${result.method}</title>
<style>
  body { font-family: Georgia, 'Times New Roman', serif; color: #111; padding: 40px; max-width: 720px; margin: 0 auto; }
  h1 { font-size: 20px; border-bottom: 2px solid #0083AB; padding-bottom: 8px; }
  pre { font-family: 'Courier New', monospace; white-space: pre-wrap; font-size: 13px; line-height: 1.5; }
</style></head><body>
<h1>${result.method}</h1><pre>${report.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre>
</body></html>`);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
    setShowMenu(false);
  };

  return (
    <div className="relative">
      <button
        onClick={() => setShowMenu(!showMenu)}
        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-neutral-300 dark:border-neutral-700 text-sm font-medium text-neutral-600 dark:text-neutral-400 hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-colors"
      >
        <Download className="w-4 h-4" />
        Export
      </button>

      {showMenu && (
        <div className="absolute right-0 top-full mt-1 w-48 bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 rounded-xl shadow-modal p-1 z-10">
          <button
            onClick={handleCopy}
            className="w-full flex items-center gap-2 px-3 py-2 rounded-lg text-sm text-neutral-700 dark:text-neutral-300 hover:bg-neutral-100 dark:hover:bg-neutral-800 transition-colors"
          >
            <Clipboard className="w-4 h-4" />
            Copy to Clipboard
          </button>
          <button
            onClick={handleDownloadPDF}
            className="w-full flex items-center gap-2 px-3 py-2 rounded-lg text-sm text-neutral-700 dark:text-neutral-300 hover:bg-neutral-100 dark:hover:bg-neutral-800 transition-colors"
          >
            <Download className="w-4 h-4" />
            Download PDF
          </button>
        </div>
      )}
    </div>
  );
}
